### ISSUE TITLE
I getting only a fully white color in depth screen

### ISSUE THREAD

**Issue by vigneshgig** [aliyasineser/stereoDepth#3]
I done all step for stereo calibration but I getting a just a white screen then I tried your stereo calibration file it's working it showing  some depth but it's not going to be correct depth because I am using different from your camera (two c270 camera).

this is my stereo file
%YAML:1.0
---
K1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 8.9097802803323373e+02, 0., 3.0006642964743565e+02, 0.,
       9.2593842191950148e+02, 7.8165024820505010e+01, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 4.5571307763078717e-01, -2.1371653403804274e+00,
       -1.0600088198594815e-01, -4.1709276363259854e-03,
       7.6138794069241875e+00 ]
K2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 8.8097737167946809e+02, 0., 3.3341133238820430e+02, 0.,
       9.1397906735611662e+02, 1.0851476284668595e+02, 0., 0., 1. ]
D2: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 9.2906895358031608e-02, 1.0129152698060886e+00,
       -9.5093716749191579e-02, 4.5423297986634187e-03,
       -2.3420055234373098e+00 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9981362129215290e-01, -1.7125721991468577e-02,
       -8.9124814132944419e-03, 1.6998282631813209e-02,
       9.9975491330655863e-01, -1.4183501223761859e-02,
       9.1531997815183005e-03, 1.4029360843117065e-02,
       9.9985968814033765e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 1.0577134040602316e-01, 1.4328375860577982e-03,
       -1.1656850572458893e-02 ]
E: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 2.1126148930712530e-04, 1.1674095429020535e-02,
       1.2673015875918243e-03, -1.2622824193606941e-02,
       -1.2842723192162449e-03, -1.0565260796848723e-01,
       3.6536060292735226e-04, 1.0576995563609995e-01,
       -1.4874377977337520e-03 ]
F: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.9124993696215748e-07, 1.0169253916597929e-05,
       1.6991364161982508e-04, -1.1014530791674363e-05,
       -1.0783294803252525e-06, -7.8750996918197716e-02,
       1.4228594622010579e-03, 7.7895980868225079e-02, 1. ]
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -9.9293279311101512e-01, 5.0973054514407415e-03,
       1.1856848587163883e-01, -4.2910791113344423e-03,
       -9.9996591349316033e-01, 7.0539699354129530e-03,
       1.1860040052554023e-01, 6.4953313175043813e-03,
       9.9292082044151808e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -9.9389176604265628e-01, -1.3463812346450965e-02,
       1.0953484901943035e-01, 1.2771990513931762e-02,
       -9.9989382612060951e-01, -7.0151795558210583e-03,
       1.0961767034069771e-01, -5.5733511452202037e-03,
       9.9395820038173144e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 3.7013994770355175e+01, 0., 6.1154418468475342e+01, 0., 0.,
       3.7013994770355175e+01, 5.5961920452117920e+02, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 3.7013994770355175e+01, 0., 6.1154418468475342e+01,
       -3.9390806669324721e+00, 0., 3.7013994770355175e+01,
       5.5961920452117920e+02, 0., 0., 0., 1., 0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., -6.1154418468475342e+01, 0., 1., 0.,
       -5.5961920452117920e+02, 0., 0., 0., 3.7013994770355175e+01, 0.,
       0., 9.3966074574399450e+00, 0. ]

square_size 0.025 m 9 6 chessboard

what I missed

thanks

**Comment by aliyasineser** [comment]
You missed nothing I assume. Stereo calibration is a nutshell. Please be sure that your cameras not moving and have the exact same axis. Also check your calibration images because if there is a blurry part for example, it may effect the calibration process. Calibration dataset is very important, please start with 10 good image pairs and increase it with different perspectives. Close and varied angles are important as I know. I am sure on one thing, you need to check your database tens to hunreds times because it is very weird. Code is tested many times. And please check preview before posting the issue, It is hard to read.

**Comment by fh-kriftel** [comment]
First I would like to mention, that this code works very nicely for my 35mm fischertechnik construction set cameras. 
Regarding the all white depth map. If it is not all totally white but only mostly and if you have a few all black small spots or areas as well, then apply a little gaussian blur before running the stereo calculation.
